### PR TITLE
Fixed unreachable if

### LINKED ISSUE #2: elif unreachable
The condition in [this line](https://github.com/nhsx/covid19-app-system-public/blob/a41ee3c966c4f59ff0b1e7c3ff8aeb70b1c2d312/src/aws/lambdas/advanced_analytics/advanced_analytics.py#L72) will never be triggered since it is subsumed by the `if`; any number greater than 500 is already greater than 300. Perhaps replace the `elif` by an `if`.

### PR DESCRIPTION
**Pull request by rdelfin**
Fixes #2

### CODE REVIEW

**Comment by javierhonduco** [comment]
:ship:

**Comment by nhs-covid19** [comment]
Thank you for your contribution to the NHS Covid-19 application. As this is not the primary working copy of the source code, we cannot apply the patch to this repository, otherwise it will diverge from the upstream code. If and when we fix the issue  upstream it will become available in this repository at the next software release.

**Comment by Relequestual** [comment]
@nhs-covid19 FYI, if you're not accepting PRs, you can disable them for this project, avoiding peoples confusion.

**Comment by nhs-covid19** [comment]
Hi @Relequestual - Thanks for your quick reply. I was not aware of this. The issue https://github.com/dear-github/dear-github/issues/84 appears to indicate that this isn't the case.

**Pull request closed without merging**
